//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BikeClubLib.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Member
	{
        //private object p;

        /*public Member(string id, DateTime birthDate, DateTime enrollmentDate, string iBAN, string login, string name, string password)
        {
            BirthDate = birthDate;
            
            EnrollmentDate = enrollmentDate;
            IBAN = iBAN;
            Login = login;
            Name = name;
            Password = password;
        }*/

        public string Name
		{
			get;
			set;
		}

		public string IBAN
		{
			get;
			set;
		}

		public string ID
		{
			get;
			set;
		}

		public DateTime EnrollmentDate
		{
			get;
			set;
		}

		public DateTime? CancellationDate
		{
			get;
			set;
		}

		public DateTime BirthDate
		{
			get;
			set;
		}

		public string Login
		{
			get;
			set;
		}

		public string Password
		{
			get;
			set;
		}

		public virtual ICollection<Payment> Payments
		{
			get;
			set;
		}

		public virtual Member Parent
		{
			get;
			set;
		}

		public virtual ICollection<Member> Children
		{
			get;
			set;
		}

        [InverseProperty("Member")]
		public virtual ICollection<Votes> Votes
		{
			get;
			set;
		}

        [InverseProperty("Members")]
		public virtual ICollection<Event> Events
		{
			get;
			set;
		}

        [InverseProperty("Responsible")]
		public virtual ICollection<Event> ProposedEvents
		{
			get;
			set;
		}

	}
}

