//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BikeClubLib.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.ComponentModel.DataAnnotations;

	public partial class Club
	{
        private string v1;
        private int v2;

        public Club(string v1, int v2)
        {
            this.v1 = v1;
            this.v2 = v2;
        }

        public double Quota
		{
			get;
			set;
		}


        [Key]
        public string Name
		{
			get;
			set;
		}

		public virtual ICollection<Member> Members
		{
			get;
			set;
		}

		public virtual Member ActualPresident
		{
			get;
			set;
		}

		public virtual ICollection<Member> Vocals
		{
			get;
			set;
		}

		public virtual ICollection<Election> Elections
		{
			get;
			set;
		}

		public virtual Member Treasurer
		{
			get;
			set;
		}

	}
}

